name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "include/**"
      - "tests/**"
      - "assets/**"
      - "meson.build"
      - "meson_options.txt"
      - "Makefile"
      - "compile_commands.json"
      - "nix/**"
      - "scripts/**"
      - "Doxyfile"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "include/**"
      - "tests/**"
      - "assets/**"
      - "meson.build"
      - "meson_options.txt"
      - "Makefile"
      - "compile_commands.json"
      - "nix/**"
      - "scripts/**"
      - "Doxyfile"

jobs:
  native-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          flakehub: false

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Build
        run: nix develop ./nix --command make build

      - name: Test
        run: nix develop ./nix --command make test

  cross-builds:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, windows, wasm]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          flakehub: false

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Cross build (${{ matrix.arch }})
        run: nix develop ./nix#${{ matrix.arch }} --command make cross-${{ matrix.arch }}
